# CloudFlare Worker Configuration for Epilogue API Proxy
name = "epilogue-api-proxy"
main = "cloudflare-worker.js"
compatibility_date = "2024-01-01"

# Environment variables (set these in CloudFlare dashboard)
[vars]
DAILY_LIMIT = "20"

# KV Namespace binding for rate limiting
# Create this in CloudFlare dashboard first, then add the binding
# [[kv_namespaces]]
# binding = "RATE_LIMIT_KV"
# id = "your-kv-namespace-id"

# Secrets (set via wrangler or CloudFlare dashboard)
# wrangler secret put APP_SECRET
# wrangler secret put PERPLEXITY_API_KEY